
spring:
  datasource:
    url: jdbc:h2:mem:prices
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
